[tools]
atuin = "18.12.1"
difftastic = "0.67.0"
docker-cli = "29.3.0"
jj = "0.39.0"
jjui = "0.10.1"
tree-sitter = "0.26.6"
zellij = "0.43.1"
bun = "1.3.10"
go = "1.26.1"
node = "25.8.0"
poetry = "2.3.2"
usage = "2.18.2"
dust = "1.2.4"
eza = "0.23.4"
lazydocker = "0.24.4"
python = "3.14.3"
opencode = "1.2.24"
fzf = "0.70.0"
zoxide = "0.9.9"
lazygit = "0.60.0"
fd = "10.4.2"
xh = "0.25.3"
"cargo:somo" = "latest"
"cargo:bacon" = "latest"
ripgrep = "15.1.0"
jq = "1.8.1"
stylua = "2.4.0"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"github:pythops/impala" = "latest"
"github:pythops/bluetui" = "latest"
"asdf:neovim" = "0.11.6"
pitchfork = "2.0.0"
mold = "2.40.4"
bat = "0.26.1"
zig = "master"
sccache = "0.14.0"

[settings]
experimental = true

[settings.npm]
package_manager = "bun"
